// Minecraft constants aligned with cubiomes (biomes.h, util.c, finders.h).

// Numeric ids match cubiomes enum MCVersion in biomes.h.
export type MinecraftVersion = { id: number; label: string; name: string };
export const MINECRAFT_VERSIONS: MinecraftVersion[] = [
  { id: 34, label: "26.2 (latest)", name: "Chaos Cubed" },
  { id: 33, label: "26.1", name: "Tiny Takeover" },
  { id: 32, label: "1.21.11", name: "Mounts of Mayhem" },
  { id: 31, label: "1.21.9", name: "The Copper Age" },
  { id: 30, label: "1.21.6", name: "Chase the Skies" },
  { id: 29, label: "1.21.5", name: "Spring to Life" },
  { id: 28, label: "1.21.4", name: "The Garden Awakens" },
  { id: 27, label: "1.21.3", name: "Tricky Trials" },
  { id: 26, label: "1.21.1", name: "Tricky Trials" },
  { id: 25, label: "1.20", name: "Trails & Tales" },
  { id: 24, label: "1.19", name: "The Wild Update" },
  { id: 23, label: "1.19.2", name: "The Wild Update" },
  { id: 22, label: "1.18 (1.18.2)", name: "Caves & Cliffs: Part II" },
  { id: 21, label: "1.17 (1.17.1)", name: "Caves & Cliffs: Part I" },
  { id: 20, label: "1.16", name: "Nether Update" },
  { id: 19, label: "1.16.1", name: "Nether Update" },
  { id: 18, label: "1.15 (1.15.2)", name: "Buzzy Bees" },
  { id: 17, label: "1.14 (1.14.4)", name: "Village & Pillage" },
  { id: 16, label: "1.13 (1.13.2)", name: "Aquatic Update" },
  { id: 15, label: "1.12 (1.12.2)", name: "World of Color Update" },
  { id: 14, label: "1.11 (1.11.2)", name: "Exploration Update" },
  { id: 13, label: "1.10 (1.10.2)", name: "Frostburn Update" },
  { id: 12, label: "1.9 (1.9.4)", name: "Combat Update" },
  { id: 11, label: "1.8 (1.8.9)", name: "Bountiful Update" },
  { id: 2, label: "1.8 (Beta)", name: "Adventure Update" },
  { id: 10, label: "1.7 (1.7.10)", name: "The Update that Changed the World" },
  { id: 1, label: "1.7 (Beta)", name: "Beta 1.7" },
  { id: 9, label: "1.6 (1.6.4)", name: "Horse Update" },
  { id: 8, label: "1.5 (1.5.2)", name: "Redstone Update" },
  { id: 7, label: "1.4 (1.4.7)", name: "Pretty Scary Update" },
  { id: 6, label: "1.3 (1.3.2)", name: "Easy" },
  { id: 5, label: "1.2 (1.2.5)", name: "Pretty" },
  { id: 4, label: "1.1 (1.1.0)", name: "1.1" },
  { id: 3, label: "1.0 (1.0.0)", name: "Official Release" },
];

export const BIOME_HEIGHTS = [
  { label: "Surface", value: 256 },
  { label: "Nether Roof", value: 128 },
  { label: "Sea Level", value: 63 },
  { label: "Underground", value: 0 },
  { label: "Bottom", value: -64 },
] as const;

export const BIOME_SCALING = [1, 4, 16, 64, 256] as const;

export const DIMENSIONS = [
  { label: "Overworld", value: 0 },
  { label: "Nether", value: -1 },
  { label: "End", value: 1 },
] as const;

// TODO: add mc version released in
export type Biome = { id: number; label: string; dimension: number; color: string };
export const BIOMES: Biome[] = [
  { id: 0, label: "Ocean", dimension: 0, color: "#000070" },
  { id: 1, label: "Plains", dimension: 0, color: "#8DB360" },
  { id: 2, label: "Desert", dimension: 0, color: "#FA9418" },
  { id: 3, label: "Windswept Hills", dimension: 0, color: "#606060" },
  { id: 4, label: "Forest", dimension: 0, color: "#056621" },
  { id: 5, label: "Taiga", dimension: 0, color: "#0B6659" },
  { id: 6, label: "Swamp", dimension: 0, color: "#07F9B2" },
  { id: 7, label: "River", dimension: 0, color: "#0000FF" },
  { id: 8, label: "Nether Wastes", dimension: -1, color: "#BF3B3B" },
  { id: 9, label: "The End", dimension: 1, color: "#8080FF" },
  { id: 10, label: "Frozen Ocean", dimension: 0, color: "#7070D6" },
  { id: 11, label: "Frozen River", dimension: 0, color: "#A0A0FF" },
  { id: 12, label: "Snowy Plains", dimension: 0, color: "#FFFFFF" },
  { id: 13, label: "Snowy Mountains", dimension: 0, color: "#A0A0A0" },
  { id: 14, label: "Mushroom Fields", dimension: 0, color: "#FF00FF" },
  { id: 15, label: "Mushroom Field Shore", dimension: 0, color: "#A000FF" },
  { id: 16, label: "Beach", dimension: 0, color: "#FADE55" },
  { id: 17, label: "Desert Hills", dimension: 0, color: "#D25F12" },
  { id: 18, label: "Wooded Hills", dimension: 0, color: "#22551C" },
  { id: 19, label: "Taiga Hills", dimension: 0, color: "#163933" },
  { id: 20, label: "Mountain Edge", dimension: 0, color: "#72789A" },
  { id: 21, label: "Jungle", dimension: 0, color: "#537B09" },
  { id: 22, label: "Jungle Hills", dimension: 0, color: "#2C4205" },
  { id: 23, label: "Sparse Jungle", dimension: 0, color: "#628B17" },
  { id: 24, label: "Deep Ocean", dimension: 0, color: "#000030" },
  { id: 25, label: "Stony Shore", dimension: 0, color: "#A2A284" },
  { id: 26, label: "Snowy Beach", dimension: 0, color: "#FAF0C0" },
  { id: 27, label: "Birch Forest", dimension: 0, color: "#307444" },
  { id: 28, label: "Birch Forest Hills", dimension: 0, color: "#1F5F32" },
  { id: 29, label: "Dark Forest", dimension: 0, color: "#40511A" },
  { id: 30, label: "Snowy Taiga", dimension: 0, color: "#31554A" },
  { id: 31, label: "Snowy Taiga Hills", dimension: 0, color: "#243F36" },
  { id: 32, label: "Old Growth Pine Taiga", dimension: 0, color: "#596651" },
  { id: 33, label: "Giant Tree Taiga Hills", dimension: 0, color: "#454F3E" },
  { id: 34, label: "Windswept Forest", dimension: 0, color: "#507050" },
  { id: 35, label: "Savanna", dimension: 0, color: "#BDB25F" },
  { id: 36, label: "Savanna Plateau", dimension: 0, color: "#A79D64" },
  { id: 37, label: "Badlands", dimension: 0, color: "#D94515" },
  { id: 38, label: "Wooded Badlands", dimension: 0, color: "#B09765" },
  { id: 39, label: "Badlands Plateau", dimension: 0, color: "#CA8C65" },
  { id: 40, label: "Small End Islands", dimension: 1, color: "#8080FF" },
  { id: 41, label: "End Midlands", dimension: 1, color: "#8080FF" },
  { id: 42, label: "End Highlands", dimension: 1, color: "#8080FF" },
  { id: 43, label: "End Barrens", dimension: 1, color: "#8080FF" },
  { id: 44, label: "Warm Ocean", dimension: 0, color: "#0000AC" },
  { id: 45, label: "Lukewarm Ocean", dimension: 0, color: "#000090" },
  { id: 46, label: "Cold Ocean", dimension: 0, color: "#202070" },
  { id: 47, label: "Deep Warm Ocean", dimension: 0, color: "#000050" },
  { id: 48, label: "Deep Lukewarm Ocean", dimension: 0, color: "#000040" },
  { id: 49, label: "Deep Cold Ocean", dimension: 0, color: "#202038" },
  { id: 50, label: "Deep Frozen Ocean", dimension: 0, color: "#404090" },
  { id: 51, label: "Seasonal Forest", dimension: 0, color: "#2F560F" },
  { id: 52, label: "Rainforest", dimension: 0, color: "#47840E" },
  { id: 53, label: "Shrubland", dimension: 0, color: "#789E31" },
  { id: 127, label: "The Void", dimension: 0, color: "#000000" },
  { id: 129, label: "Sunflower Plains", dimension: 0, color: "#B5DB88" },
  { id: 130, label: "Desert Lakes", dimension: 0, color: "#FFBC40" },
  { id: 131, label: "Windswept Gravelly Hills", dimension: 0, color: "#888888" },
  { id: 132, label: "Flower Forest", dimension: 0, color: "#2D8E49" },
  { id: 133, label: "Taiga Mountains", dimension: 0, color: "#338E81" },
  { id: 134, label: "Swamp Hills", dimension: 0, color: "#2FFFDA" },
  { id: 140, label: "Ice Spikes", dimension: 0, color: "#B4DCDC" },
  { id: 149, label: "Modified Jungle", dimension: 0, color: "#7BA331" },
  { id: 151, label: "Modified Jungle Edge", dimension: 0, color: "#8AB33F" },
  { id: 155, label: "Old Growth Birch Forest", dimension: 0, color: "#589C6C" },
  { id: 156, label: "Tall Birch Hills", dimension: 0, color: "#47875A" },
  { id: 157, label: "Dark Forest Hills", dimension: 0, color: "#687942" },
  { id: 158, label: "Snowy Taiga Mountains", dimension: 0, color: "#597D72" },
  { id: 160, label: "Old Growth Spruce Taiga", dimension: 0, color: "#818E79" },
  { id: 161, label: "Giant Spruce Taiga Hills", dimension: 0, color: "#6D7766" },
  { id: 162, label: "Modified Gravelly Mountains", dimension: 0, color: "#789878" },
  { id: 163, label: "Windswept Savanna", dimension: 0, color: "#E5DA87" },
  { id: 164, label: "Shattered Savanna Plateau", dimension: 0, color: "#CFC58C" },
  { id: 165, label: "Eroded Badlands", dimension: 0, color: "#FF6D3D" },
  { id: 166, label: "Modified Wooded Badlands Plateau", dimension: 0, color: "#D8BF8D" },
  { id: 167, label: "Modified Badlands Plateau", dimension: 0, color: "#F2B48D" },
  { id: 168, label: "Bamboo Jungle", dimension: 0, color: "#768E14" },
  { id: 169, label: "Bamboo Jungle Hills", dimension: 0, color: "#3B470A" },
  { id: 170, label: "Soul Sand Valley", dimension: -1, color: "#5E3830" },
  { id: 171, label: "Crimson Forest", dimension: -1, color: "#DD0808" },
  { id: 172, label: "Warped Forest", dimension: -1, color: "#49907B" },
  { id: 173, label: "Basalt Deltas", dimension: -1, color: "#403636" },
  { id: 174, label: "Dripstone Caves", dimension: 0, color: "#4E3012" },
  { id: 175, label: "Lush Caves", dimension: 0, color: "#283C00" },
  { id: 177, label: "Meadow", dimension: 0, color: "#60A445" },
  { id: 178, label: "Grove", dimension: 0, color: "#47726C" },
  { id: 179, label: "Snowy Slopes", dimension: 0, color: "#C4C4C4" },
  { id: 180, label: "Jagged Peaks", dimension: 0, color: "#DCDCC8" },
  { id: 181, label: "Frozen Peaks", dimension: 0, color: "#B0B3CE" },
  { id: 182, label: "Stony Peaks", dimension: 0, color: "#7B8F74" },
  { id: 183, label: "Deep Dark", dimension: 0, color: "#031F29" },
  { id: 184, label: "Mangrove Swamp", dimension: 0, color: "#2CCC8E" },
  { id: 185, label: "Cherry Grove", dimension: 0, color: "#FF91C8" },
  { id: 186, label: "Pale Garden", dimension: 0, color: "#696D95" },
  { id: 187, label: "Sulfur Caves", dimension: 0, color: "#C8D232" },
].sort((a, b) => a.label.localeCompare(b.label));

// TODO: add mc version released in
export type Structure = { id: number; label: string; dimension: number };
export const STRUCTURES: Structure[] = [
  { id: 1, label: "Desert Pyramid", dimension: 0 },
  { id: 2, label: "Jungle Pyramid", dimension: 0 },
  { id: 3, label: "Swamp Hut", dimension: 0 },
  { id: 4, label: "Igloo", dimension: 0 },
  { id: 5, label: "Village", dimension: 0 },
  { id: 6, label: "Ocean Ruin", dimension: 0 },
  { id: 7, label: "Shipwreck", dimension: 0 },
  { id: 8, label: "Monument", dimension: 0 },
  { id: 9, label: "Mansion", dimension: 0 },
  { id: 10, label: "Pillager Outpost", dimension: 0 },
  { id: 11, label: "Ruined Portal", dimension: 0 },
  { id: 12, label: "Ruined Portal Nether", dimension: -1 },
  { id: 13, label: "Ancient City", dimension: 0 },
  { id: 14, label: "Buried Treasure", dimension: 0 },
  { id: 15, label: "Mineshaft", dimension: 0 },
  { id: 16, label: "Desert Well", dimension: 0 },
  { id: 17, label: "Amethyst Geode", dimension: 0 },
  { id: 18, label: "Fortress", dimension: -1 },
  { id: 19, label: "Bastion Remnant", dimension: -1 },
  { id: 20, label: "End City", dimension: 1 },
  { id: 21, label: "End Gateway", dimension: 1 },
  // { id: 22, label: "End Island", dimension: 1 },
  { id: 23, label: "Trail Ruins", dimension: 0 },
  { id: 24, label: "Trial Chambers", dimension: 0 },
  { id: 25, label: "Stronghold", dimension: 0 },
].sort((a, b) => a.label.localeCompare(b.label));
