// Minecraft constants aligned with cubiomes (biomes.h, util.c, finders.h).

export type MinecraftVersionEntry = { id: number; label: string; version: string };

// Numeric ids match cubiomes enum MCVersion in biomes.h.
export const MINECRAFT_VERSIONS: MinecraftVersionEntry[] = [
  { id: 3, label: "1.0", version: "1.0.0" },
  { id: 4, label: "1.1", version: "1.1.0" },
  { id: 5, label: "1.2", version: "1.2.5" },
  { id: 6, label: "1.3", version: "1.3.2" },
  { id: 7, label: "1.4", version: "1.4.7" },
  { id: 8, label: "1.5", version: "1.5.2" },
  { id: 9, label: "1.6", version: "1.6.4" },
  { id: 1, label: "1.7 (Beta)", version: "1.7" },
  { id: 10, label: "1.7", version: "1.7.10" },
  { id: 2, label: "1.8 (Beta)", version: "1.8" },
  { id: 11, label: "1.8", version: "1.8.9" },
  { id: 12, label: "1.9", version: "1.9.4" },
  { id: 13, label: "1.10", version: "1.10.2" },
  { id: 14, label: "1.11", version: "1.11.2" },
  { id: 15, label: "1.12", version: "1.12.2" },
  { id: 16, label: "1.13", version: "1.13.2" },
  { id: 17, label: "1.14", version: "1.14.4" },
  { id: 18, label: "1.15", version: "1.15.2" },
  { id: 19, label: "1.16.1", version: "1.16.1" },
  { id: 20, label: "1.16", version: "1.16" },
  { id: 21, label: "1.17", version: "1.17.1" },
  { id: 22, label: "1.18", version: "1.18.2" },
  { id: 23, label: "1.19.2", version: "1.19.2" },
  { id: 24, label: "1.19", version: "1.19" },
  { id: 25, label: "1.20", version: "1.20" },
  { id: 26, label: "1.21.1", version: "1.21.1" },
  { id: 27, label: "1.21.3", version: "1.21.3" },
  { id: 28, label: "1.21 (Latest)", version: "1.21" },
];

export const DEFAULT_VERSION = MINECRAFT_VERSIONS[MINECRAFT_VERSIONS.length - 1];

export const BIOME_HEIGHT_PRESETS = { seaLevel: 63, underground: 16, bottom: -51 } as const;
export type BiomeHeightLabel = keyof typeof BIOME_HEIGHT_PRESETS;
export const BIOME_HEIGHT_LABELS = Object.keys(BIOME_HEIGHT_PRESETS) as BiomeHeightLabel[];
export const DEFAULT_BIOME_HEIGHT = BIOME_HEIGHT_PRESETS.seaLevel;

export const BIOME_SAMPLING_SCALES = [1, 4, 16, 64, 256] as const;
export type BiomeSamplingScale = (typeof BIOME_SAMPLING_SCALES)[number];

export const DIMENSIONS = ["overworld", "nether", "end"] as const;
export type DimensionLiteral = (typeof DIMENSIONS)[number];

export type BiomeEntry = { id: number; label: string; dimension: DimensionLiteral; color: string };

export const BIOMES: BiomeEntry[] = [
  { id: 0, label: "Ocean", dimension: "overworld", color: "#000070" },
  { id: 1, label: "Plains", dimension: "overworld", color: "#8DB360" },
  { id: 2, label: "Desert", dimension: "overworld", color: "#FA9418" },
  { id: 3, label: "Windswept Hills", dimension: "overworld", color: "#606060" },
  { id: 4, label: "Forest", dimension: "overworld", color: "#056621" },
  { id: 5, label: "Taiga", dimension: "overworld", color: "#0B6659" },
  { id: 6, label: "Swamp", dimension: "overworld", color: "#07F9B2" },
  { id: 7, label: "River", dimension: "overworld", color: "#0000FF" },
  { id: 8, label: "Nether Wastes", dimension: "nether", color: "#BF3B3B" },
  { id: 9, label: "The End", dimension: "end", color: "#8080FF" },
  { id: 10, label: "Frozen Ocean", dimension: "overworld", color: "#7070D6" },
  { id: 11, label: "Frozen River", dimension: "overworld", color: "#A0A0FF" },
  { id: 12, label: "Snowy Plains", dimension: "overworld", color: "#FFFFFF" },
  { id: 13, label: "Snowy Mountains", dimension: "overworld", color: "#A0A0A0" },
  { id: 14, label: "Mushroom Fields", dimension: "overworld", color: "#FF00FF" },
  { id: 15, label: "Mushroom Field Shore", dimension: "overworld", color: "#A000FF" },
  { id: 16, label: "Beach", dimension: "overworld", color: "#FADE55" },
  { id: 17, label: "Desert Hills", dimension: "overworld", color: "#D25F12" },
  { id: 18, label: "Wooded Hills", dimension: "overworld", color: "#22551C" },
  { id: 19, label: "Taiga Hills", dimension: "overworld", color: "#163933" },
  { id: 20, label: "Mountain Edge", dimension: "overworld", color: "#72789A" },
  { id: 21, label: "Jungle", dimension: "overworld", color: "#537B09" },
  { id: 22, label: "Jungle Hills", dimension: "overworld", color: "#2C4205" },
  { id: 23, label: "Sparse Jungle", dimension: "overworld", color: "#628B17" },
  { id: 24, label: "Deep Ocean", dimension: "overworld", color: "#000030" },
  { id: 25, label: "Stony Shore", dimension: "overworld", color: "#A2A284" },
  { id: 26, label: "Snowy Beach", dimension: "overworld", color: "#FAF0C0" },
  { id: 27, label: "Birch Forest", dimension: "overworld", color: "#307444" },
  { id: 28, label: "Birch Forest Hills", dimension: "overworld", color: "#1F5F32" },
  { id: 29, label: "Dark Forest", dimension: "overworld", color: "#40511A" },
  { id: 30, label: "Snowy Taiga", dimension: "overworld", color: "#31554A" },
  { id: 31, label: "Snowy Taiga Hills", dimension: "overworld", color: "#243F36" },
  { id: 32, label: "Old Growth Pine Taiga", dimension: "overworld", color: "#596651" },
  { id: 33, label: "Giant Tree Taiga Hills", dimension: "overworld", color: "#454F3E" },
  { id: 34, label: "Windswept Forest", dimension: "overworld", color: "#507050" },
  { id: 35, label: "Savanna", dimension: "overworld", color: "#BDB25F" },
  { id: 36, label: "Savanna Plateau", dimension: "overworld", color: "#A79D64" },
  { id: 37, label: "Badlands", dimension: "overworld", color: "#D94515" },
  { id: 38, label: "Wooded Badlands", dimension: "overworld", color: "#B09765" },
  { id: 39, label: "Badlands Plateau", dimension: "overworld", color: "#CA8C65" },
  { id: 40, label: "Small End Islands", dimension: "end", color: "#8080FF" },
  { id: 41, label: "End Midlands", dimension: "end", color: "#8080FF" },
  { id: 42, label: "End Highlands", dimension: "end", color: "#8080FF" },
  { id: 43, label: "End Barrens", dimension: "end", color: "#8080FF" },
  { id: 44, label: "Warm Ocean", dimension: "overworld", color: "#0000AC" },
  { id: 45, label: "Lukewarm Ocean", dimension: "overworld", color: "#000090" },
  { id: 46, label: "Cold Ocean", dimension: "overworld", color: "#202070" },
  { id: 47, label: "Deep Warm Ocean", dimension: "overworld", color: "#000050" },
  { id: 48, label: "Deep Lukewarm Ocean", dimension: "overworld", color: "#000040" },
  { id: 49, label: "Deep Cold Ocean", dimension: "overworld", color: "#202038" },
  { id: 50, label: "Deep Frozen Ocean", dimension: "overworld", color: "#404090" },
  { id: 51, label: "Seasonal Forest", dimension: "overworld", color: "#2F560F" },
  { id: 52, label: "Rainforest", dimension: "overworld", color: "#47840E" },
  { id: 53, label: "Shrubland", dimension: "overworld", color: "#789E31" },
  { id: 127, label: "The Void", dimension: "overworld", color: "#000000" },
  { id: 129, label: "Sunflower Plains", dimension: "overworld", color: "#B5DB88" },
  { id: 130, label: "Desert Lakes", dimension: "overworld", color: "#FFBC40" },
  { id: 131, label: "Windswept Gravelly Hills", dimension: "overworld", color: "#888888" },
  { id: 132, label: "Flower Forest", dimension: "overworld", color: "#2D8E49" },
  { id: 133, label: "Taiga Mountains", dimension: "overworld", color: "#338E81" },
  { id: 134, label: "Swamp Hills", dimension: "overworld", color: "#2FFFDA" },
  { id: 140, label: "Ice Spikes", dimension: "overworld", color: "#B4DCDC" },
  { id: 149, label: "Modified Jungle", dimension: "overworld", color: "#7BA331" },
  { id: 151, label: "Modified Jungle Edge", dimension: "overworld", color: "#8AB33F" },
  { id: 155, label: "Old Growth Birch Forest", dimension: "overworld", color: "#589C6C" },
  { id: 156, label: "Tall Birch Hills", dimension: "overworld", color: "#47875A" },
  { id: 157, label: "Dark Forest Hills", dimension: "overworld", color: "#687942" },
  { id: 158, label: "Snowy Taiga Mountains", dimension: "overworld", color: "#597D72" },
  { id: 160, label: "Old Growth Spruce Taiga", dimension: "overworld", color: "#818E79" },
  { id: 161, label: "Giant Spruce Taiga Hills", dimension: "overworld", color: "#6D7766" },
  { id: 162, label: "Modified Gravelly Mountains", dimension: "overworld", color: "#789878" },
  { id: 163, label: "Windswept Savanna", dimension: "overworld", color: "#E5DA87" },
  { id: 164, label: "Shattered Savanna Plateau", dimension: "overworld", color: "#CFC58C" },
  { id: 165, label: "Eroded Badlands", dimension: "overworld", color: "#FF6D3D" },
  { id: 166, label: "Modified Wooded Badlands Plateau", dimension: "overworld", color: "#D8BF8D" },
  { id: 167, label: "Modified Badlands Plateau", dimension: "overworld", color: "#F2B48D" },
  { id: 168, label: "Bamboo Jungle", dimension: "overworld", color: "#768E14" },
  { id: 169, label: "Bamboo Jungle Hills", dimension: "overworld", color: "#3B470A" },
  { id: 170, label: "Soul Sand Valley", dimension: "nether", color: "#5E3830" },
  { id: 171, label: "Crimson Forest", dimension: "nether", color: "#DD0808" },
  { id: 172, label: "Warped Forest", dimension: "nether", color: "#49907B" },
  { id: 173, label: "Basalt Deltas", dimension: "nether", color: "#403636" },
  { id: 174, label: "Dripstone Caves", dimension: "overworld", color: "#4E3012" },
  { id: 175, label: "Lush Caves", dimension: "overworld", color: "#283C00" },
  { id: 177, label: "Meadow", dimension: "overworld", color: "#60A445" },
  { id: 178, label: "Grove", dimension: "overworld", color: "#47726C" },
  { id: 179, label: "Snowy Slopes", dimension: "overworld", color: "#C4C4C4" },
  { id: 180, label: "Jagged Peaks", dimension: "overworld", color: "#DCDCC8" },
  { id: 181, label: "Frozen Peaks", dimension: "overworld", color: "#B0B3CE" },
  { id: 182, label: "Stony Peaks", dimension: "overworld", color: "#7B8F74" },
  { id: 183, label: "Deep Dark", dimension: "overworld", color: "#031F29" },
  { id: 184, label: "Mangrove Swamp", dimension: "overworld", color: "#2CCC8E" },
  { id: 185, label: "Cherry Grove", dimension: "overworld", color: "#FF91C8" },
  { id: 186, label: "Pale Garden", dimension: "overworld", color: "#696D95" },
];

export type StructureEntry = { id: number; label: string; dimension: DimensionLiteral };

export const STRUCTURES: StructureEntry[] = [
  { id: 1, label: "Desert Pyramid", dimension: "overworld" },
  { id: 2, label: "Jungle Pyramid", dimension: "overworld" },
  { id: 3, label: "Swamp Hut", dimension: "overworld" },
  { id: 4, label: "Igloo", dimension: "overworld" },
  { id: 5, label: "Village", dimension: "overworld" },
  { id: 6, label: "Ocean Ruin", dimension: "overworld" },
  { id: 7, label: "Shipwreck", dimension: "overworld" },
  { id: 8, label: "Monument", dimension: "overworld" },
  { id: 9, label: "Mansion", dimension: "overworld" },
  { id: 10, label: "Pillager Outpost", dimension: "overworld" },
  { id: 11, label: "Ruined Portal", dimension: "overworld" },
  { id: 12, label: "Ruined Portal Nether", dimension: "nether" },
  { id: 13, label: "Ancient City", dimension: "overworld" },
  { id: 14, label: "Buried Treasure", dimension: "overworld" },
  { id: 15, label: "Mineshaft", dimension: "overworld" },
  { id: 16, label: "Desert Well", dimension: "overworld" },
  { id: 17, label: "Amethyst Geode", dimension: "overworld" },
  { id: 18, label: "Fortress", dimension: "nether" },
  { id: 19, label: "Bastion Remnant", dimension: "nether" },
  { id: 20, label: "End City", dimension: "end" },
  { id: 21, label: "End Gateway", dimension: "end" },
  { id: 22, label: "End Island", dimension: "end" },
  { id: 23, label: "Trail Ruins", dimension: "overworld" },
  { id: 24, label: "Trial Chambers", dimension: "overworld" },
];
